"""add error message to pipeline runs

Revision ID: 439fd769cc54
Revises: 6a5c2fa2007f
Create Date: 2026-08-08 19:45:54.022244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '439fd769cc54'
down_revision = '6a5c2fa2007f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=225),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=225),
               existing_nullable=False)

    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.drop_column('error_message')

    # ### end Alembic commands ###
