"""Add anime tracking fields

Revision ID: 6a5c2fa2007f
Revises: 
Create Date: 2026-07-15 15:16:34.799863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a5c2fa2007f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anime', schema=None) as batch_op:
        batch_op.add_column(sa.Column('airing_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('content_rating', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('total_episodes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('watch_status', sa.String(length=30), server_default="Plan to watch", nullable=False))
        batch_op.add_column(sa.Column('episodes_watched', sa.Integer(), server_default="0", nullable=False))
        batch_op.add_column(sa.Column('user_rating', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anime', schema=None) as batch_op:
        batch_op.drop_column('user_rating')
        batch_op.drop_column('episodes_watched')
        batch_op.drop_column('watch_status')
        batch_op.drop_column('total_episodes')
        batch_op.drop_column('content_rating')
        batch_op.drop_column('airing_status')

    # ### end Alembic commands ###
